{% set name = "colour-science" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colour_science-{{ version }}.tar.gz
  sha256: 29a8d4c67104dafeebcd7c942f31e0935e356527a265aa81c4164ab34dd69b66

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python >=3.9,<3.12
    - imageio >=2,<3
    - numpy >=1.20,<2
    - scipy >=1.7,<2
    - typing_extensions >=4,<5
    - matplotlib-base >=3.4,!=3.5.0,!=3.5.1

test:
  imports:
    - colour
    - colour.colorimetry
    - colour.io
    - colour.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.colour-science.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
