{% set name = "colour-science" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colour_science-{{ version }}.tar.gz
  sha256: a3cb3b8e8a51db82b62524173d65ae70396bfa943636e111e50fb7cc125857ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python >=3.9,<3.13
    - imageio >=2,<3
    - numpy >=1.22,<2
    - scipy >=1.8,<2
    - typing_extensions >=4,<5
    - matplotlib-base >=3.5,!=3.5.0,!=3.5.1

test:
  imports:
    - colour
    - colour.colorimetry
    - colour.io
    - colour.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.colour-science.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
